export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience level, and specific focus areas. Everything is personalized to help you prepare smarter, not harder."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered, detailed explanations whenever you need them."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top. Keep your learning organized and make it your own."
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Go beyond memorizing answers—unlock detailed concept explanations generated by AI. Truly master each topic by understanding the reasoning behind it."
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and seamlessly pick up your preparation where you left off."
  }
];
