export const CARD_BG = [
  { id: 1,  bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2,  bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3,  bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4,  bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)' },
  { id: 5,  bgcolor: 'linear-gradient(135deg, #e7f0fe 0%, #f4fafd 100%)' }, // fixed typo (#e7föfe → #e7f0fe)
  { id: 6,  bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7,  bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)' },
  { id: 8,  bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)' },
  { id: 9,  bgcolor: 'linear-gradient(135deg, #f8ecff 0%, #f7f5ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' }
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience level, and specific focus areas. Everything is personalized to help you prepare smarter, not harder."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered, detailed explanations whenever you need them."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top. Keep your learning organized and make it your own."
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Go beyond memorizing answers—unlock detailed concept explanations generated by AI. Truly master each topic by understanding the reasoning behind it."
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and seamlessly pick up your preparation where you left off."
  }
];
